### ISSUE TITLE
Unable To Compile

### ISSUE THREAD

**Issue by mgiannoni** [OpenWIS/open-dj-am-install-scripts#8]
Attempt to compile OpenDJ:

> [ivy:retrieve] 	  http://download.oracle.com/maven/org/forgerock/opendj/opendj-server2x-adapter/2.6.0/opendj-server2x-adapter-2.6.0.pom
> [ivy:retrieve] 	  -- artifact org.forgerock.opendj#opendj-server2x-adapter;2.6.0!opendj-server2x-adapter.jar:
> [ivy:retrieve] 	  http://download.oracle.com/maven/org/forgerock/opendj/opendj-server2x-adapter/2.6.0/opendj-server2x-adapter-2.6.0.jar
> [ivy:retrieve] 		::::::::::::::::::::::::::::::::::::::::::::::
> [ivy:retrieve] 		::          UNRESOLVED DEPENDENCIES         ::
> [ivy:retrieve] 		::::::::::::::::::::::::::::::::::::::::::::::
> [ivy:retrieve] 		:: org.forgerock.opendj#opendj-rest2ldap-servlet;2.6.0: not found
> [ivy:retrieve] 		:: org.forgerock.opendj#opendj-server2x-adapter;2.6.0: not found
> [ivy:retrieve] 		::::::::::::::::::::::::::::::::::::::::::::::
> [ivy:retrieve] 
> [ivy:retrieve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
> 

Attempt to compile OpenAM:

> [ERROR] Failed to execute goal on project openam-shared: 
> Could not resolve dependencies for project 
> org.forgerock.openam:openam-shared:jar:12.0.0: 
> Failed to collect dependencies at org.forgerock.commons:json-fluent:jar:2.4.2: 
> Failed to read artifact descriptor for org.forgerock.commons:json-fluent:jar:2.4.2: 
> Could not transfer artifact org.forgerock.commons:json-fluent:pom:2.4.2 from/to forgerock-staging-repo (http://maven.forgerock.org/repo/releases): 
> Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

There is a thread about about a similar problem compiling OpenAM and OpenDJ on the ForgeRock community:

https://forum.forgerock.com/topic/openam-source-code-compilation-error/

Since the ForgeRock products support a community version, the dounload and build should be allowed (doesn't break any licensing).  There are two links in the thread to scripts that can perform the compile.  They appear to build up the various components from several public GitHub resources, and avoid the authorization barrier.  

OpenDJ Build:
https://gist.github.com/aldaris/fe234d76f3940c42ae9bb5aa69b8e98e

OpenAM Build:
https://gist.github.com/aldaris/6a630fb77ada352f4b3bb5f1144892df

**Comment by rogers492** [comment]
Closed by PR for : https://github.com/OpenWIS/openwis/issues/278
